Add USD metric
Crocussys/Distributed_computing_systems-7_semester-hello_git pull request #4
Opened 2023-10-02 14:06 UTC by Crocussys

2023-10-05 18:21 UTC, yasha-nev commented on README.md
> +`[metric_names]` - может быть названием метрики, или списком метрик через пробел, или `all` для всех метрик сразу
мне кажется можно указать какие метрики писать в командах, а то это не очевидно.

2023-10-05 18:26 UTC, yasha-nev commented on metrics.py
> +
А тут не нужен .join()? Или можно оставить так и ошибки не будет? А если нажать start/stop несколько раз, у нас не будет несколько висящих потоков? Или в python это не так работает?

2023-10-05 18:31 UTC, Crocussys commented on metrics.py
> +
Наоборот. Если тут поставить self.__thread.join(), то всё как раз таки повиснет, так как он будет ожидать завершение всех потоков в этой точке.
Несколько висящих потоков быть не должно. За это отвечает self.__collecting_flag

2023-10-05 18:33 UTC, Crocussys commented on README.md
> +`[metric_names]` - может быть названием метрики, или списком метрик через пробел, или `all` для всех метрик сразу
Так как система является расширяемой, разработчик сам указывает название метрик.

2023-10-05 18:36 UTC, yasha-nev commented on metrics.py
> +
Так а после, как только флаг станет false, цикл завершится, можно ловить, не?

2023-10-05 18:37 UTC, yasha-nev commented on README.md
> +`[metric_names]` - может быть названием метрики, или списком метрик через пробел, или `all` для всех метрик сразу
Ну сейчас то какие то метрики собираются

2023-10-05 18:38 UTC, Crocussys commented on metrics.py
> +
Тогда такой вопрос. А где его ловить?

2023-10-05 18:51 UTC, yasha-nev commented on metrics.py
> +
Ну так наверное, flag = false, thread.join(), thread = None

2023-10-05 18:51 UTC, yasha-nev commented on metrics.py
> +
А вообще я у себя проверил, поидее поток завершится тут и ловить не надо в этом случае

2023-10-05 18:52 UTC, yasha-nev commented on metrics.py
> +
Но вдруг не завершится, а пользователь еще несколько создаст

2023-10-05 18:53 UTC, yasha-nev commented on metrics.py
> +
Можно мнение сюда Артема Валерьевича

2023-10-05 19:55 UTC, Crocussys commented on metrics.py
> +
flag = false ОК
thread.join() Теперь мы ждём, когда всё другое закончится, но другое не закончится. Как минимум поток, отвечающий за консоль. Всё программа зависла.
А новый не создастся. За это отвечает self.__collecting_flag (строка 78)

2023-10-05 20:15 UTC, yasha-nev commented on metrics.py
> +
thread.join блокирует только тот поток в котором новый поток был инициализирован, поэтому да, если у тебя не закончился поток, который создался в строке 80, то главный поток в котором новый был создан зависнит, в данном случае это поток отвечающий за консоли

2023-10-05 20:15 UTC, yasha-nev commented on metrics.py
> +
Но почему у тебя поток не завершается? когда ты flag = false делаешь?

2023-10-05 20:15 UTC, yasha-nev commented on metrics.py
> +
Смысл тогда от него?

2023-10-05 20:16 UTC, yasha-nev commented on metrics.py
> +
Цикл while flag должен завершится

2023-10-05 20:17 UTC, yasha-nev commented on metrics.py
> +
Плюс, если новый не завершился, потом забыть про него и плодить кучу новых, не знаю

2023-10-19 18:17 UTC, arybin93 requested changes
В целом хорошо, но есть, что поправить.
Ещё можешь, посмотреть в сторону написания unit tests, например модуль pytest.

2023-10-19 18:17 UTC, arybin93 commented on README.md
> +- `exit` - выйти из программы
Хорошо бы написать какие требования для запуска программы, например, от какой версии python?

2023-10-19 18:17 UTC, arybin93 commented on README.md
> +- `stop [metric_names]` - прекратить собирать метрику
Это лучше настроить через аргументы командной строки и параметры, так же хорошо бы, что бы help работал.
Посмотри в сторону https://docs.python.org/3/library/argparse.html

Команда для запуска твоего кода и прикрепи скриншот с примером работы программы.

Описание, куда сохраняются собранные метрики. 
Привести список доступных метрик и описание их

2023-10-19 18:17 UTC, arybin93 commented on README.md
> +`[metric_names]` - может быть названием метрики, или списком метрик через пробел, или `all` для всех метрик сразу
Возможность через параметр посмотреть доступные метрики, argparse

2023-10-19 18:17 UTC, arybin93 commented on metrics.py
> +class CounterKeys:
Когда создаёшь классы у которых должны быть реализованы одинаковые методы, можно использовать абстрактный класс, модуль abc, в нём описать методы.
Классы метрик, наследуются от абстрактного класса и реализуют нужные методы.

2023-10-19 18:17 UTC, arybin93 commented on main.py
> +    inp = input().split(" ")
Управление через консоль, один раз запускается сборщик метрик.
Метрики собираются каждую минуту, сохраняются в файл.
Пользователь не знает про методы start/stop/collecting/clean, пользователю нужно просто запустить сборщик и получить файл с метриками. Эти методы уже сама программа использует в зависимости от логики.

При запуске, старт. при остановке стоп. cleanip происходит после сохранения в файл, чтобы обнулить счётчик и за следующий интервал посчитать значения.

2023-11-06 16:14 UTC, arybin93 approved these changes
Вроде бы всё выглядит хорошо, спасибо)
можно мёржить)

2023-11-06 16:14 UTC, arybin93 commented on README.md
> +# Описание
Хорошее описание)

2023-11-06 16:14 UTC, arybin93 commented on metrics.py
> +class Metric(ABC):
Всё таки попробовал abc, круто)

2023-11-06 16:22 UTC, merged